# Generated by Django 5.2.7 on 2025-11-03 14:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Expense amount (must be positive)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='channel_id',
            field=models.CharField(db_index=True, help_text='Telegram channel ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.CharField(db_index=True, help_text='Telegram user ID', max_length=255),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id', 'date'], name='Finance_exp_user_id_880156_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user_id', 'category'], name='Finance_exp_user_id_464e41_idx'),
        ),
    ]
